version: "latest"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ppl
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pplbase
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: